export { default as MarketingSlider6 } from './paas_app_ilustracia-114 1.png'
export { default as MarketingSlider5 } from './paas_app_ilustracia-115 3.png'
export { default as MarketingSlider4 } from './paas_app_ilustracia-116 1.png'
export { default as MarketingSlider2 } from './paas_app_ilustracia-117 1.png'
export { default as MarketingSlider1 } from './paas_app_ilustracia-118 2.png'
export { default as MarketingSlider3 } from './paas_app_ilustracia2-113 1.png'
