on:
  push:
    tags:
      - 'prod**'
      - 'staging**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_UPDATE_MESSAGE: '${{ github.event.ref }} ${{ github.event.head_commit.message }}'
    steps:
      - name: 🚂 Setup repo
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: 🚛 Setup Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 24
          cache: npm

      - name: 🚧 Setup EAS
        uses: expo/expo-github-action@c7b66a9c327a43a8fa7c0158e7f30d6040d2481e # v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_BUILD_TOKEN }}

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🚀 Build production
        if: contains(github.event.ref, 'prod') && !contains(github.event.ref, 'ota')
        run: |
          PROFILE="prod"
          if [[ ${{ github.event.ref }} == *"test"* ]]; then
            PROFILE="${PROFILE}-test"
          fi
          eas build --profile "$PROFILE" --platform all --auto-submit --non-interactive

      - name: 🚀 Update production
        if: contains(github.event.ref, 'prod') && contains(github.event.ref, 'ota')
        run: |
          PROFILE="prod"
          if [[ ${{ github.event.ref }} == *"test"* ]]; then
            PROFILE="${PROFILE}-test"
          fi
          eas update --message "$EXPO_UPDATE_MESSAGE" --branch "$PROFILE" --platform all --non-interactive --clear-cache

      - name: 🚀 Build staging
        if: contains(github.event.ref, 'staging')
        run: eas build --profile staging --platform all --auto-submit --non-interactive
