on:
  push:
    tags:
      - 'prod**'
      - 'staging**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🚂 Setup repo
        uses: actions/checkout@v4

      - name: 🚛 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: 🚧 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_BUILD_TOKEN }}

      - name: 📦 Install dependencies
        run: yarn install

      - name: 🚀 Build production
        if: contains(github.event.ref, 'prod') && !contains(github.event.ref, 'ota')
        run: |
          if  [[ ${{ github.event.ref }} == *"test"* ]]; then
            eas build --profile prod-test --platform all --auto-submit --non-interactive
          else
            eas build --profile prod --platform all --auto-submit --non-interactive
          fi

      - name: 🚀 Update production
        if: contains(github.event.ref, 'prod') && contains(github.event.ref, 'ota')
        run: |
          if [[ ${{ github.event.ref }} == *"test"* ]]; then
            eas update --message "${{ github.event.ref }} ${{ github.event.head_commit.message }}" --branch prod-test --platform all --non-interactive
          else
            eas update --message "${{ github.event.ref }} ${{ github.event.head_commit.message }}" --branch prod --platform all --non-interactive
          fi

      - name: 🚀 Build staging
        if: contains(github.event.ref, 'staging')
        run: eas build --profile staging --platform all --auto-submit --non-interactive
