name: Validate

on: [pull_request]

jobs:
  typescript-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '24'
          cache: npm

      - run: npm ci

      - name: Typescript check
        run: npm run ts:check

      - name: ESlint check
        uses: sibiraj-s/action-eslint@v2
        with:
          eslint-args: '--ignore-path=.gitignore --quiet'
          extensions: 'md,ts,tsx'
          annotations: true
